version: '3'

services:
  stream:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'stream'
    restart: always
    volumes:
      - stream-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: userstream
      POSTGRES_PASSWORD: passworduser

volumes:
  stream-data:
